# Generated by Django 3.2.4 on 2021-07-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('verified', models.BooleanField(null=True)),
                ('categories', models.ManyToManyField(to='main.Category')),
            ],
        ),
    ]
