# Generated by Django 3.2.4 on 2021-07-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samples',
            name='item',
        ),
        migrations.AddField(
            model_name='samples',
            name='item_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
